# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1
    instance:
      data:
        enabled: false
    credentials:
      instanceProfile: false
      profileName: default 